### ISSUE TITLE
ZLib issue

### ISSUE THREAD

**Issue by skwerlman** [Kraigie/nostrum#45] opened 2018-02-27 03:42 UTC
Seems very similar to #35 

```
22:26:44.468 [info]  websocket closed, attempting reconnect

22:26:44.470 [error] GenServer #PID<0.800.0> terminating
** (stop) :data_error
    :zlib.inflateEnd_nif(#Reference<0.2579208287.1398407170.85146>)
    (nostrum) lib/nostrum/shard/session.ex:133: Nostrum.Shard.Session.handle_info/2
    (stdlib) gen_server.erl:633: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:703: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:gun_down, #PID<0.803.0>, :ws, :closed, [], []}
State: %{gateway: 'gateway.discord.gg', gun_pid: #PID<0.803.0>, heartbeat_ack: true, producer_pid: #PID<0.801.0>, reconnect_attempts: 0, seq: 22, session: "2f2a3e582935ec8bb82d20bdf207446a", shard_num: 0, shard_pid: #PID<0.800.0>, token: "<CENSORED>", zlib_buffer: "", zlib_ctx: #Reference<0.2579208287.1398407170.85146>}

22:26:44.471 [info]  GenStage consumer #PID<0.857.0> is stopping after receiving cancel from producer #PID<0.802.0> with reason: {:data_error, [{:zlib, :inflateEnd_nif, [#Reference<0.2579208287.1398407170.85146>], []}, {Nostrum.Shard.Session, :handle_info, 2, [file: 'lib/nostrum/shard/session.ex', line: 133]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 633]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 703]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}
```

**Comment by Kraigie** [comment] 2018-02-27 16:32
The last issue was because the user's internet would drop, do you believe this could be the case here?

**Comment by sibsibsib** [comment] 2018-02-28 16:56
I ran into this as well. It seems to be a lifecycle issue with the zlib state, and lack of error handling. I was able to work around by replacing the `:zlib.close` calls with `:zlib.inflateReset` and catching any errors, but im not sure if that's the right solution.

**Comment by Kraigie** [comment] 2018-02-28 19:05
Can you reliably reproduce this issue?

Last time I tried, manually killing the process wouldn't lead to this behavior, and I'm not in an environment that'll allow me to disconnect my internet to test (which was the case with the previous error). The issue is definitely with the state of the zlib ctx, but to really close this out I want to make sure any fix we come up with will work, hence needing a way to reproduce. 

I'm not sure how useful it will be to discuss potential fixes until we can reproduce, but this is definitely something I want to get fixed!

**Comment by sibsibsib** [comment] 2018-02-28 23:55
I’ll see if i can manually trigger something 🤔

**Comment by skwerlman** [comment] 2018-03-03 17:26
hey, sorry for the late reply.

I am unable to reproduce this reliably, though it does still occur.

I've tried to reproduce it by manually unplugging the internet at various locations, restarting my router, and resetting the networking service on the host machine, (all while the bot ran) but none of those triggered this error. If you have any other ideas on how I might be able to repro this, I will try them.

**Comment by Kraigie** [comment] 2018-03-16 15:44
As a stopgap measure, I'll likely add a config option to avoid using zlib as it's not required. I'll leave this open until the issue is fully resolved.

**Comment by barkerja** [comment] 2018-04-03 14:49
Experienced this issue overnight, and it does appear to be due to losing connectivity.

```
04:14:55.879 [error] GenServer #PID<0.237.0> terminating
** (stop) :data_error
    :zlib.inflateEnd_nif(#Reference<0.1518309513.3002990599.98253>)
    (nostrum) lib/nostrum/shard/session.ex:135: Nostrum.Shard.Session.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:gun_down, #PID<0.240.0>, :ws, :closed, [], []}

04:14:55.882 [error] GenServer #PID<0.266.0> terminating
** (stop) :data_error
    :zlib.inflateEnd_nif(#Reference<0.1518309513.3002990599.98253>)
    (nostrum) lib/nostrum/shard/session.ex:135: Nostrum.Shard.Session.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.1518309513.3002859522.98456>, :process, #PID<0.239.0>, {:data_error, [{:zlib, :inflateEnd_nif, [#Reference<0.1518309513.3002990599.98253>], []}, {Nostrum.Shard.Session, :handle_info, 2, [file: 'lib/nostrum/shard/session.ex', line: 135]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}

04:43:48.664 [error] GenServer #PID<0.891.0> terminating
** (stop) :data_error
    :zlib.inflateEnd_nif(#Reference<0.1518309513.3002990597.97833>)
    (nostrum) lib/nostrum/shard/session.ex:135: Nostrum.Shard.Session.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:gun_down, #PID<0.894.0>, :ws, :closed, [], []}
```

I have been using Nostrum as part of my journey to learn Elixir, so my experience here is limited. Is there an appropriate solution to automatically restart the process?

(P.S. Thank you for a great bot! Hopefully one day I will be able contribute)

**Comment by Kraigie** [comment] 2018-04-04 20:48
Sorry for the late reply! With e9d0622629f4731ec0dbc3d61a63756030d0a7f3 zlib_streaming is now **opt in**, and you can do so through your config. You can find info on it [here](e9d0622629f4731ec0dbc3d61a63756030d0a7f3). It will no longer be used as the default until this is ironed out. 

The process should be restarted automatically, but the zlib erlang lib uses a port, and that may be getting lost somewhere, or causing other issues? Definitely something I could check out if I could somehow invoke these disconnects w/o unplugging my Ethernet, but even that looks unreliable.

Lets leave this open until the issue is fully resolved.

**Comment by barkerja** [comment] 2018-04-04 20:50
This happened again this afternoon, but it doesn’t appear to be due to loss
of connectivity on my end but rather a closure of the websocket connection
by discord.

**Comment by Kraigie** [comment] 2018-04-17 09:01
Hey all, I've pushed some changes with 2a75a2fe86feda016c94be9a97cb15b2bc803ffa, and through my testing I haven't had any errors. This doesn't mean it's fixed, but if crashes do occur it won't leave your processes hanging and will be able to recover. If you could, enable the `zlib-stream` option and see if you run into any more problems. I'll leave this open until no one has reported any issues for a while.

For the record I was able to produce *some* zlib errors by manually killing the gun process and fiddling with it's state through IEx. Hard to say whether they're the exact same errors you all have been getting.

**Comment by Kraigie** [comment] 2018-06-17 08:43
I haven't seen any issues related to this since the changes. I'll close this for now. Let me know if any of you have seen been seeing otherwise.

**Closed by Kraigie** 2018-06-17 08:43 UTC
