### ISSUE TITLE
Consumer.start_link types

### ISSUE THREAD

**Issue by amiralies** [Kraigie/nostrum#167] opened 2020-05-25 12:22 UTC
I've a consumer (the example from readme).
Dialyzer says start_link has no local return

```elixir
  def start_link do
    Nostrum.Consumer.start_link(__MODULE__)
  end
```

**Comment by jchristgit** [comment] 2021-07-18 16:32
I can't reproduce this on master. I assume that it's probably been fixed by something else, but if not, could you re-open? I also had no Dialyzer complaint on my bot regarding this.

**Closed by jchristgit** 2021-07-18 16:32 UTC
